In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [ ]:
df = pd.read_csv("flats_houses_v1.csv")

In [ ]:
df.shape

(7470, 36)

In [ ]:
df.duplicated().sum()

28

In [ ]:
df.drop_duplicates(inplace = True)

In [ ]:
df.head(1)

,PROP_ID,PREFERENCE,PROPERTY_TYPE,PROP_NAME,DESCRIPTION,CITY_NAME,BUILDING_NAME,LOCALITY_NAME,GATED,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,BATHROOM_NUM,BATHROOM_ATTACHED,BALCONY_NUM,BALCONY_ATTACHED,CAPACITY,SHARING_COUNT,BUILTUP_SQFT,CARPET_SQFT,SUPERBUILTUP_SQFT,FURNISH,FURNISHING_ATTRIBUTES,FACING,AGE,FLOOR_NUM,TOTAL_FLOOR,FEATURES,LATITUDE,LONGITUDE,AVAILABILITY,SUB_AVAILABILITY,CORNER_PROPERTY,AVG_PRICE,PRICE_SQFT,AMENITIES
0,G71293060,S,Residential Apartment,Unity Group The Amaryllis,Unity Group The Amaryllis is a ready to move ...,Central Delhi,Unity Group The Amaryllis,Karol Bagh,NaN,New Booking,Freehold,6.0,0,NaN,NaN,NaN,NaN,NaN,NaN,3173.0,NaN,NaN,NaN,NaN,5,1,32.0,N,28.657811,77.19466,Under Construction,Not Mentioned,NaN,103000000,32461,[]

In [ ]:
df.drop(columns = ["PROP_NAME", "BUILDING_NAME", "CAPACITY", "SHARING_COUNT", "AGE"], inplace = True)

In [ ]:
df.head(2)

,PROP_ID,PREFERENCE,PROPERTY_TYPE,DESCRIPTION,CITY_NAME,LOCALITY_NAME,GATED,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,BATHROOM_NUM,BATHROOM_ATTACHED,BALCONY_NUM,BALCONY_ATTACHED,BUILTUP_SQFT,CARPET_SQFT,SUPERBUILTUP_SQFT,FURNISH,FURNISHING_ATTRIBUTES,FACING,FLOOR_NUM,TOTAL_FLOOR,FEATURES,LATITUDE,LONGITUDE,AVAILABILITY,SUB_AVAILABILITY,CORNER_PROPERTY,AVG_PRICE,PRICE_SQFT,AMENITIES
0,G71293060,S,Residential Apartment,Unity Group The Amaryllis is a ready to move ...,Central Delhi,Karol Bagh,NaN,New Booking,Freehold,6.0,0,NaN,NaN,NaN,NaN,3173.0,NaN,NaN,NaN,NaN,1,32.0,N,28.657811,77.19466,Under Construction,Not Mentioned,NaN,103000000,32461,[]
1,Y71293054,S,Residential Apartment,Own a 5 BHK apartment in Unity Group The Amar...,Central Delhi,Karol Bagh,NaN,New Booking,Freehold,5.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,32.0,N,28.657811,77.19466,Under Construction,Not Mentioned,NaN,102983146,32461,[]

In [ ]:
df.dropna(subset=["AVG_PRICE"], inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7442 entries, 0 to 7469
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   PROP_ID                7442 non-null   object
 1   PREFERENCE             7442 non-null   object
 2   PROPERTY_TYPE          7442 non-null   object
 3   DESCRIPTION            7442 non-null   object
 4   CITY_NAME              7442 non-null   object
 5   LOCALITY_NAME          7442 non-null   object
 6   GATED                  3394 non-null   object
 7   TRANSACT_TYPE          7442 non-null   object
 8   OWNTYPE                7442 non-null   object
 9   BEDROOM_NUM            7441 non-null   float64
 10  BATHROOM_NUM           7442 non-null   int64
 11  BATHROOM_ATTACHED      3533 non-null   object
 12  BALCONY_NUM            7241 non-null   float64
 13  BALCONY_ATTACHED       3533 non-null   object
 14  BUILTUP_SQFT           2782 non-null   float64
 15  CARPET_SQFT            3510 non-null   float64
 16  SUPERBUILTUP_SQFT      2782 non-null   float64
 17  FURNISH                6542 non-null   object
 18  FURNISHING_ATTRIBUTES  4933 non-null   object
 19  FACING                 4682 non-null   object
 20  FLOOR_NUM              4937 non-null   object
 21  TOTAL_FLOOR            7376 non-null   float64
 22  FEATURES               7442 non-null   object
 23  LATITUDE               7442 non-null   float64
 24  LONGITUDE              7442 non-null   float64
 25  AVAILABILITY           7442 non-null   object
 26  SUB_AVAILABILITY       7442 non-null   object
 27  CORNER_PROPERTY        2551 non-null   object
 28  AVG_PRICE              7442 non-null   int64
 29  PRICE_SQFT             7442 non-null   int64
 30  AMENITIES              7442 non-null   object
dtypes: float64(8), int64(3), object(20)
memory usage: 1.8+ MB

In [ ]:
def treat_price(x):
  x = x/10000000
  return round(x, 2)

In [ ]:
df["AVG_PRICE_CR"] = df["AVG_PRICE"].apply(treat_price)

In [ ]:
df.head()

,PROP_ID,PREFERENCE,PROPERTY_TYPE,DESCRIPTION,CITY_NAME,LOCALITY_NAME,GATED,TRANSACT_TYPE,OWNTYPE,BEDROOM_NUM,BATHROOM_NUM,BATHROOM_ATTACHED,BALCONY_NUM,BALCONY_ATTACHED,BUILTUP_SQFT,CARPET_SQFT,SUPERBUILTUP_SQFT,FURNISH,FURNISHING_ATTRIBUTES,FACING,FLOOR_NUM,TOTAL_FLOOR,FEATURES,LATITUDE,LONGITUDE,AVAILABILITY,SUB_AVAILABILITY,CORNER_PROPERTY,AVG_PRICE,PRICE_SQFT,AMENITIES,AVG_PRICE_CR
0,G71293060,S,Residential Apartment,Unity Group The Amaryllis is a ready to move ...,Central Delhi,Karol Bagh,NaN,New Booking,Freehold,6.0,0,NaN,NaN,NaN,NaN,3173.0,NaN,NaN,NaN,NaN,1,32.0,N,28.657811,77.19466,Under Construction,Not Mentioned,NaN,103000000,32461,[],10.30
1,Y71293054,S,Residential Apartment,Own a 5 BHK apartment in Unity Group The Amar...,Central Delhi,Karol Bagh,NaN,New Booking,Freehold,5.0,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,32.0,N,28.657811,77.19466,Under Construction,Not Mentioned,NaN,102983146,32461,[],10.30
2,D71293050,S,Residential Apartment,Book your 4 BHK flat in Unity Group The Amary...,Central Delhi,Karol Bagh,NaN,New Booking,Freehold,4.0,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,32.0,N,28.657811,77.19466,Under Construction,Not Mentioned,NaN,62362438,33233,[],6.24
3,B71293046,S,Residential Apartment,Own a 3 BHK apartment in Unity Group The Amar...,Central Delhi,Karol Bagh,NaN,New Booking,Freehold,3.0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,32.0,N,28.657811,77.19466,Under Construction,Not Mentioned,NaN,30500000,30214,[],3.05
4,A71293042,S,Residential Apartment,Unity Group The Amaryllis offers 2 BHK flats ...,Central Delhi,Karol Bagh,NaN,New Booking,Freehold,2.0,2,NaN,NaN,NaN,NaN,741.0,NaN,NaN,NaN,NaN,1,32.0,N,28.657811,77.19466,Under Construction,Not Mentioned,NaN,19500156,26316,[],1.95

In [ ]:
df = df[~df["BEDROOM_NUM"].isnull()]

In [ ]:
# df = df[df["AVAILABILITY"] != "Under Construction"]

In [ ]:
def floor_num_fun(floor_num):
  if floor_num == 'L':
    return '0'
  elif floor_num == 'B':
    return '-1'
  elif floor_num == 'G':
    return '0'
  elif floor_num == 'M':
    return '3'
  else:
    return floor_num

In [ ]:
df["FLOOR_NUM"] = df["FLOOR_NUM"].apply(floor_num_fun)

In [ ]:
df["FLOOR_NUM"].value_counts()

In [ ]:
df["FACING"].isnull().sum()

2760

In [ ]:
df["FACING"].fillna("NA", inplace = True)

In [ ]:
df["AREA_SQFT"] = df["AVG_PRICE"]/df["PRICE_SQFT"]

In [ ]:
df[["AREA_SQFT", "BUILTUP_SQFT", "CARPET_SQFT", "SUPERBUILTUP_SQFT"]][100:120]

In [ ]:
def prop_type_fun(property_type):
  if property_type == "Residential Apartment":
    return "flat"
  elif property_type == "Independent House/Villa":
    return "house"

df["PROPERTY_TYPE"] = df["PROPERTY_TYPE"].apply(prop_type_fun)

In [ ]:
df.to_csv("flat_houses_v2.csv", index = False)

In [ ]:
df.shape

(7441, 33)